# Generated by Django 4.2.1 on 2023-10-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_remove_lisiting_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('Count', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
