# Generated by Django 4.2.1 on 2023-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bookings_alter_bid_bid_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ingredients', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('food_type', models.BinaryField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
