# Generated by Django 4.2.1 on 2023-10-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_food_food_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_type',
            new_name='Non_veg',
        ),
    ]
