# Generated by Django 4.2.1 on 2023-10-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_food_a_img_alter_food_b_img_alter_food_c_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=250)),
                ('phn', models.IntegerField()),
                ('train_no', models.IntegerField()),
                ('seat_no', models.IntegerField()),
                ('station', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
                ('cash_on_delivery', models.BooleanField()),
                ('journey_date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
