# Generated by Django 4.2.1 on 2023-10-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_foodbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbookings',
            name='cash_on_delivery',
        ),
    ]
