# Generated by Django 4.2.1 on 2023-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_bid_remove_listing_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=250)),
                ('train_no', models.IntegerField()),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('route', models.CharField(max_length=1000)),
                ('b_ac', models.IntegerField()),
                ('b_gen', models.IntegerField()),
                ('b_sit', models.IntegerField()),
                ('seats_in_ac', models.IntegerField()),
                ('seats_in_gen', models.IntegerField()),
                ('seats_in_sit', models.IntegerField()),
            ],
        ),
    ]
