# Generated by Django 4.2.1 on 2023-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='ending',
            field=models.CharField(default='ABH', max_length=100),
        ),
        migrations.AddField(
            model_name='train',
            name='starting',
            field=models.CharField(default='ABH', max_length=100),
        ),
    ]
