# Generated by Django 4.2.1 on 2023-10-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_train_ending_train_starting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Train_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='numb', to='auctions.train'),
        ),
    ]
