# Generated by Django 4.2.1 on 2023-10-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_bookings_train_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='train_no',
        ),
    ]
