# Generated by Django 4.2.1 on 2023-10-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_bookings_train_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
