# Generated by Django 4.2.1 on 2023-10-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='train_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.train'),
        ),
    ]
